pipeline {
  agent any

  triggers {
    pollSCM('* * * * *') // Jenkins akan mengecek perubahan di GitHub setiap 1 menit atau cron syntax
  }

  environment {
    REPO_URL = 'https://github.com/alghoziii/mini-soccer-booking.git'
    SERVICE_DIR = 'user-service-main'
    IMAGE_NAME = 'user-service'
    DOCKER_CREDENTIALS = credentials('docker-credential')
    SSH_KEY = credentials('ssh-key')
    HOST = credentials('host')
    USERNAME = credentials('username')
  }

  stages {
    stage('Check Commit Message') {
      steps {
        script {
          def commitMessage = sh(
            script: "git log -1 --pretty=%B",
            returnStdout: true
          ).trim()

          echo "Commit Message: ${commitMessage}"
          if (commitMessage.contains("[skip ci]")) {
            echo "Skipping pipeline due to [skip ci] tag in commit message."
            currentBuild.result = 'ABORTED'
            return
          }
        }
      }
    }

    stage('Set Target Branch') {
      steps {
        script {
          if (env.GIT_BRANCH == 'origin/main' || env.GIT_BRANCH == 'main') {
            env.TARGET_BRANCH = 'main'
          } else if (env.GIT_BRANCH == 'origin/development' || env.GIT_BRANCH == 'development') {
            env.TARGET_BRANCH = 'development'
          } else {
            env.TARGET_BRANCH = 'main'
          }
          echo "TARGET_BRANCH: ${env.TARGET_BRANCH}"
        }
      }
    }

    stage('Login to Docker Hub') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'docker-credential', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
            sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
          }
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        dir("${env.SERVICE_DIR}") {
          script {
            def runNumber = currentBuild.number
            sh "docker build -t ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber} ."
            sh "docker push ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber}"
          }
        }
      }
    }

    stage('Deploy Locally') {
      steps {
        dir("${env.SERVICE_DIR}") {
          script {
            def runNumber = currentBuild.number
            
            if (!fileExists('.env')) {
                sh 'cp .env.example .env'
            }

            sh "docker rm -f user-service || true"
            sh "docker run -d --name user-service --env-file .env -p 8001:8001 ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber}"
          }
        }
      }
    }
  }

  post {
    success {
      echo "Pipeline completed successfully."
    }
  }
}
