pipeline {
  agent any

  environment {
    REPO_URL = 'https://github.com/alghoziii/mini-soccer-booking.git'
    SERVICE_DIR = 'user-service-main'
    IMAGE_NAME = 'user-service'
    DOCKER_CREDENTIALS = credentials('docker-credential')
    SSH_KEY = credentials('ssh-key')
    HOST = credentials('host')
    USERNAME = credentials('username')
  }

  stages {
    stage('Check Commit Message') {
      steps {
        script {
          def commitMessage = sh(
            script: "git log -1 --pretty=%B",
            returnStdout: true
          ).trim()

          echo "Commit Message: ${commitMessage}"
          if (commitMessage.contains("[skip ci]")) {
            echo "Skipping pipeline due to [skip ci] tag in commit message."
            currentBuild.result = 'ABORTED'
            return
          }
        }
      }
    }

    stage('Set Target Branch') {
      steps {
        script {
          if (env.GIT_BRANCH == 'origin/main' || env.GIT_BRANCH == 'main') {
            env.TARGET_BRANCH = 'main'
          } else if (env.GIT_BRANCH == 'origin/development' || env.GIT_BRANCH == 'development') {
            env.TARGET_BRANCH = 'development'
          } else {
            env.TARGET_BRANCH = 'main'
          }
          echo "TARGET_BRANCH: ${env.TARGET_BRANCH}"
        }
      }
    }

    stage('Login to Docker Hub') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'docker-credential', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
            sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
          }
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        dir("${env.SERVICE_DIR}") {
          script {
            def runNumber = currentBuild.number
            sh "docker build -t ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber} ."
            sh "docker push ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber}"
          }
        }
      }
    }

    stage('Update docker-compose.yaml') {
      steps {
        dir("${env.SERVICE_DIR}") {
          script {
            def runNumber = currentBuild.number
            sh "sed -i -E 's|image: .*/${IMAGE_NAME}:.*|image: ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber}|' docker-compose.yaml"
          }
        }
      }
    }

    stage('Commit and Push Changes') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'github-credential', usernameVariable: 'GIT_USER', passwordVariable: 'GIT_PASS')]) {
            sh """
            git config --global user.name 'Jenkins CI'
            git config --global user.email 'jenkins@company.com'
            git remote set-url origin https://\${GIT_USER}:\${GIT_PASS}@github.com/alghoziii/mini-soccer-booking.git
            git add ${env.SERVICE_DIR}/docker-compose.yaml
            git commit -m 'Update ${IMAGE_NAME} image version to ${TARGET_BRANCH}-\${currentBuild.number} [skip ci]' || echo 'No changes to commit'
            git pull origin ${TARGET_BRANCH} --rebase
            git push origin HEAD:${TARGET_BRANCH}
            """
          }
        }
      }
    }

    stage('Deploy to Remote Server') {
      steps {
        script {
          def repoDir = "/home/${USERNAME}/mini-soccer-booking"
          def serviceDir = "${repoDir}/${env.SERVICE_DIR}"
          def sshCommandToServer = """
          ssh -o StrictHostKeyChecking=no -i ${SSH_KEY} ${USERNAME}@${HOST} '
            if [ -d "${repoDir}/.git" ]; then
                echo "Directory exists. Pulling latest changes."
                cd "${repoDir}"
                git pull origin "${TARGET_BRANCH}"
            else
                echo "Directory does not exist. Cloning repository."
                git clone -b "${TARGET_BRANCH}" https://github.com/alghoziii/mini-soccer-booking.git "${repoDir}"
                cd "${repoDir}"
            fi

            cd "${serviceDir}"
            if [ ! -f .env ]; then
                cp .env.example .env
            fi
            docker compose pull || true
            docker compose up -d --force-recreate
          '
          """
          sh sshCommandToServer
        }
      }
    }
  }
}
