pipeline {
  agent any

  triggers {
    pollSCM('* * * * *')
  }

  environment {
    REPO_URL = 'https://github.com/alghoziii/mini-soccer-booking.git'
    SERVICE_DIR = 'field-service-main'
    IMAGE_NAME = 'field-service'
    DOCKER_CREDENTIALS = credentials('docker-credential')
    SSH_KEY = credentials('ssh-key')
    HOST = credentials('host')
    USERNAME = credentials('username')
  }

  stages {
    stage('Check Commit Message') {
      steps {
        script {
          def commitMessage = sh(
            script: "git log -1 --pretty=%B",
            returnStdout: true
          ).trim()

          echo "Commit Message: ${commitMessage}"
          if (commitMessage.contains("[skip ci]")) {
            echo "Skipping pipeline due to [skip ci] tag in commit message."
            currentBuild.result = 'ABORTED'
            currentBuild.delete()
            return
          }

          echo "Pipeline will continue. No [skip ci] tag found in commit message."
        }
      }
    }

    stage('Set Target Branch') {
      steps {
        script {
          echo "GIT_BRANCH: ${env.GIT_BRANCH}"
          if (env.GIT_BRANCH == 'origin/main' || env.GIT_BRANCH == 'main') {
            env.TARGET_BRANCH = 'main'
          } else if (env.GIT_BRANCH == 'origin/development' || env.GIT_BRANCH == 'development') {
            env.TARGET_BRANCH = 'development'
          } else {
            env.TARGET_BRANCH = 'main'
          }
          echo "TARGET_BRANCH: ${env.TARGET_BRANCH}"
        }
      }
    }

    stage('Checkout Code') {
      steps {
        script {
          checkout([$class: 'GitSCM',
            branches: [
              [name: "*/${env.TARGET_BRANCH}"]
            ],
            userRemoteConfigs: [
              [url: env.REPO_URL, credentialsId: 'github-credential']
            ]
          ])
        }
      }
    }

    stage('Login to Docker Hub') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'docker-credential', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
            sh """
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            """
          }
        }
      }
    }

    stage('Build and Push Docker Image') {
      steps {
        dir("${env.SERVICE_DIR}") {
          script {
            def runNumber = currentBuild.number
            sh "docker build -t ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber} ."
            sh "docker push ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber}"
          }
        }
      }
    }

    stage('Update docker-compose.yaml') {
      steps {
        dir("${env.SERVICE_DIR}") {
          script {
            def runNumber = currentBuild.number
            sh "sed -i -E 's|image: .*/${IMAGE_NAME}:.*|image: ${DOCKER_CREDENTIALS_USR}/${IMAGE_NAME}:${runNumber}|' docker-compose.yaml"
          }
        }
      }
    }

    stage('Deploy Locally') {
      steps {
        dir("${env.SERVICE_DIR}") {
          script {
            def runNumber = currentBuild.number
            
            sh 'cp .env.example .env'
            sh "sed -i 's|^TIMEZONE=.*|TIMEZONE=Asia/Jakarta|' .env"
            
            // Execute docker compose
            sh "docker-compose up -d --force-recreate"
          }
        }
      }
    }
  }
}
